<?php

// This screen only display every time the order was completed.

//insert data
/*
* order id
* product id
* product discount
* customer id
* date time
*/




$orderId = $this->getOrderId();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$order = $objectManager->create('Magento\Sales\Model\Order')->loadByIncrementId($orderId);

 $BillingAddress = $order->getBillingAddress();

$BillingAddress->getTelephone();

$shipphone = $BillingAddress->getTelephone();

 $fname = $order->getCustomerFirstname(); //name

$regphone = $this->getRegisteredPhone(); //registered

$price = $order->getGrandTotal()-00; //price

$items = $order->getAllVisibleItems();

foreach($items as $i){
    
    $i->getProductId();
    
    $i->getPrice();
    
    $_product = $objectManager->create('Magento\Catalog\Model\Product')->load($i->getProductId());
    $categoryIds = $_product->getCategoryIds();
    $prname = $_product->getName(); // product names
    
    
    $_children = $_product->getTypeInstance()->getUsedProductIds($_product);
    
    // print_r($_children);
    
        $_children1 = $objectManager->create('Magento\Catalog\Model\Product')->load($_children['0']);
    $_children1->getPrice();
     $_children2 = $objectManager->create('Magento\Catalog\Model\Product')->load($_children['1']);
    $_children2->getPrice();
     $i->getPrice();
    
    if($i->getPrice() == $_children1->getPrice()){ // for 0
        $TemplateName = "buysms_scheme";
    }elseif($i->getPrice() == $_children2->getPrice()){
       $TemplateName = "bookingsms";
    }
    
}


    $YourAPIKey='1c3c98a2-ace2-11e7-94da-0200cd936042';
$From="RKHOME";

$VAR1=$fname;   //first name
$VAR2="OrderId" .$orderId; //order id
$VAR3 = $prname;     //here is the items 
$VAR4=$price; // total price
$VAR5="https://rkhomeappliances.co.in/"; // website link



if($shipphone = $regphone){
    
$To=$regphone; //phone number from registration
    
    ### DO NOT Change anything below this line
$agent= 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.0.3705; .NET CLR 1.1.4322)';
$url = "https://2factor.in/API/V1/$YourAPIKey/ADDON_SERVICES/SEND/TSMS"; 
$ch = curl_init(); 
curl_setopt($ch,CURLOPT_URL,$url); 
curl_setopt($ch,CURLOPT_POST,true); 
curl_setopt($ch,CURLOPT_POSTFIELDS,"TemplateName=$TemplateName&From=$From&To=$To&VAR1=$VAR1&VAR2=$VAR2&VAR3=$VAR3&VAR4=$VAR4");
curl_setopt($ch, CURLOPT_USERAGENT, $agent);
echo '<div style="color:white;">';
echo curl_exec($ch); 
echo '</div>';
curl_close($ch);
    
}else{
    

    
$To=$regphone; //phone number from registration
    
    ### DO NOT Change anything below this line
$agent= 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.0.3705; .NET CLR 1.1.4322)';
$url = "https://2factor.in/API/V1/$YourAPIKey/ADDON_SERVICES/SEND/TSMS"; 
$ch = curl_init(); 
curl_setopt($ch,CURLOPT_URL,$url); 
curl_setopt($ch,CURLOPT_POST,true); 
curl_setopt($ch,CURLOPT_POSTFIELDS,"TemplateName=$TemplateName&From=$From&To=$To&VAR1=$VAR1&VAR2=$VAR2&VAR3=$VAR3&VAR4=$VAR4");
curl_setopt($ch, CURLOPT_USERAGENT, $agent);
echo '<div style="color:white;">';
echo curl_exec($ch); 
echo '</div>';
curl_close($ch);

$To=$shipphone; //phone number from ship
    
    ### DO NOT Change anything below this line
$agent= 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.0.3705; .NET CLR 1.1.4322)';
$url = "https://2factor.in/API/V1/$YourAPIKey/ADDON_SERVICES/SEND/TSMS"; 
$ch = curl_init(); 
curl_setopt($ch,CURLOPT_URL,$url); 
curl_setopt($ch,CURLOPT_POST,true); 
curl_setopt($ch,CURLOPT_POSTFIELDS,"TemplateName=$TemplateName&From=$From&To=$To&VAR1=$VAR1&VAR2=$VAR2&VAR3=$VAR3&VAR4=$VAR4");
curl_setopt($ch, CURLOPT_USERAGENT, $agent);
echo '<div style="color:white;">';
echo curl_exec($ch); 
echo '</div>';
curl_close($ch);
    

}


 $block->walletdiscount();

//   $block->walletdiscount();



?>


